function init(self) msg.post(".", "acquire_input_focus") end

function update(self, dt)
    html5.run("onDefoldUpdate()")
end

function fixed_update(self, dt)
    html5.run("onDefoldFixedUpdate()")
end

function on_input(self, action_id, action)
    if action_id == hash("touch") then
		local pressed = action.pressed and "true" or "false"
		local released = action.released and "true" or "false"
        html5.run("onDefoldInput(" .. pressed .. ", " .. released .. ")")
    end
end
